#!/usr/bin/env bash
# Transfers a file from client to server
# Takes 4 parameters:
#	The path to the file to be transferred
#	The IP of the server we want to transfer the file to
#	The username scp connects with
#	The path to the SSH private key that scp uses


if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME"
  exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

scp -o "StrictHostKeyChecking=no" -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
