#!/usr/bin/env bash
# Install and configure Nginx

# Update package list and install nginx
apt-get update -y
apt-get install -y nginx

# Configure nginx to listen on port 80 and return "Hello World!" at the root
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Start nginx
service nginx start
