#!/usr/bin/env bash
# installs nginx and configures it on a remote server for redirection and customizes 404 not found

nginx_install_and_configure() {
    sudo apt-get -y update
    sudo apt-get -y install nginx
    sudo chown -R "$USER":"$USER" /var/www/html/
    echo "Hello World!" > /var/www/html/index.html
    sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
    redirect="\\\trewrite ^/redirect_me https://rupert.id.au/python/book/learn-python3-the-hard-way-nov-15-2018.pdf permanent;"
    sudo sed -i "26i $redirect" /etc/nginx/sites-available/default

    echo "Ceci n'est pas une page" | sudo tee -a /usr/share/nginx/html/404.html
    line="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
    sudo sed -i "27i $line" /etc/nginx/sites-available/default

    if [[ $(pgrep nginx) ]]; then
	    sudo nginx -s reload
    else
	    sudo service nginx start
    fi
}
nginx_install_and_configure
