#!/usr/bin/env bash
# install and configure Nginx on multiple web servers with custom headers

nginx_install_and_configure() {
      
    # update package list and install nginx
    apt-get -y update
    apt-get install -y nginx
    ufw allow 'Nginx HTTP'

    # set up the configuration file for the default site
    sudo chown -R "$USER":"$USER" /var/www/html/
    echo "Hello World!" > /var/www/html/index.html
    sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/

    # handle redirect
    redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
    sudo sed -i "26i $redirect" /etc/nginx/sites-available/default

    # handle page_not_found
    echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
    line="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
    sudo sed -i "28i $line" /etc/nginx/sites-available/default

    # add custom header
    echo "add_header X-Served-By $(hostname);" | sudo tee -a /etc/nginx/nginx

    # reload/restart nginx server
    if [[ $(pgrep nginx) ]]; then
	    sudo nginx -s reload
    else
	    sudo service nginx start
    fi
}
nginx_install_and_configure
