#!/usr/bin/env bash
# install and configure Nginx on multiple web servers with custom headers
# Ignore SC2154 for shellcheck

nginx_install_and_configure() {
      
    # update package list and install nginx
    apt-get -y update
    apt-get install -y nginx

    # set up the configuration file for the default site
    sudo chown -R "$USER":"$USER" /var/www/html/
    echo "Hello World!" > /var/www/html/index.html
    sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
    echo "Ceci n'est pas une page" > /var/www/html/404.html

    # set up the server configurations
    server_config="server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
		server_name _;
		add_header X-Served-By \$hostname;
		location / {
			try_files $uri $uri/ =404;
		}
		location /redirect_me {
			rewrite ^ https://rupert.id.au/python/book/learn-python3-the-hard-way-nov-15-2018.pdf permanent;
		}
		error_page 404 /404.html;
		location = /404.html {
			internal;
		}
	}"
    echo -e "$server_config" > /etc/nginx/sites-available/default

    # reload/restart nginx server
    if [[ $(pgrep nginx) ]]; then
	    sudo nginx -s reload
    else
	    sudo service nginx start
    fi
}
nginx_install_and_configure
