#!/usr/bin/env bash
# script that configures a server to ensure Nginx is running and listening on port 80 of all the server’s active IPv4 IPs

# create a symlink from sites-enabled to sites-available
cp -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx
service nginx restart
