#!/usr/bin/env bash
# Shortening the fix in task 0. service (init) must say that nginx is not running
# creating the symlink and stopping nginx
cp -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx stop
