#!/usr/bin/env bash
# Shortening the fix in task 0. service (init) must say that nginx is not running

# creating the symlink
cp -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# starting nginx
service nginx stop

# sigterm to terminate the first Nginx process found
# kill "$(pgrep 'nginx' | head -1)"
