#!/usr/bin/env bash
# Get Apache to run on the container and to return a page containing
# Hello Holberton when querying the root of it

echo "ServerName localhost" | sudo tee -a /etc/apache2/apache2.conf
service apache2 restart
