#!/usr/bin/env bash
# script that configures an environment so that Nginx is running as the nginx user

# Stop nginx if it's already running
pkill apache2

# Configure nginx to listen on all active IPs on port 8080
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# Set the nginx user and group to nginx
sudo chown nginx:nginx /etc/nginx/nginx.conf

# Restrict the nginx user from using apt-get remove
chmod 700 /etc/nginx/nginx.conf

# Reload and start nginx
sudo nginx -s reload
service nginx start
