#!/usr/bin/env bash
# script that configures an environment so that Nginx is running as the nginx user
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo sed -i 's/user\s*www-data;/user nginx;/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
